#!/bin/bash
#
# Script name: work_setup
# run this script from the directory containing setup files


sudo apt update && sudo apt upgrade -y

setup_dir=$(pwd)

sudo apt install -y vim-gtk zathura texlive-full xournal sxiv mpv libreoffice
cp -r $setup_dir/.vimrc ~/
sudo cp -r $setup_dir/vim.desktop /usr/share/applications/
mkdir -p ~/.config/zathura
cp -r $setup_dir/zathurarc ~/.config/zathura/
cp -r $setup_dir/mimeapps.list ~/.config/

pip3 install --user yt-dlp 
