#!/bin/bash
#
# Script name: work_setup
# run this script from the directory containing setup files


sudo apt update && sudo apt upgrade -y

setup_dir=$(pwd)

sudo apt install -y vim-gtk zathura texlive-full xournal sxiv mpv libreoffice

echo Configure vim
cp -r $setup_dir/.vimrc ~/
sudo cp -r $setup_dir/vim.desktop /usr/share/applications/

echo Configure UltiSnips
mkdir -p ~/.vim
cp -r $setup_dir/UltiSnips ~/.vim/

echo Copy over a template for projects
mkdir -p $setup_dir/template/sources
mkdir -p ~/projects
cp -r $setup_dir/template ~/projects/

echo Configure Zathura and default applications
mkdir -p ~/.config/zathura
cp -r $setup_dir/zathurarc ~/.config/zathura/
cp -r $setup_dir/mimeapps.list ~/.config/

echo Install Qalculate!
cp -r $setup_dir/qalculate-4.6.1-x86_64.tar.xz ~/.config/
tar -xJf qalculate-4.6.1-x86_64.tar.xz
echo Press enter for each prompt:
~/.config/qalculate-4.6.1/install
sudo apt install -y gnuplot gnome-themes-extra
mkdir -p ~/.config/gtk-3.0/
cp -r $setup_dir/settings.ini ~/.config/gtk-3.0/

echo Download youtube-dlp
pip3 install --user yt-dlp

echo -e "Things to do manually to complete setup: \n \
 Create keyboard shortcut for toggling exact mode on Qalculate! \n \
 Install librewolf extensions: SingleFile, Dark Reader, Vimium-FF, BibItNow! \n \
 Customise librewolf bookmarks, search engines and cookies to be saved for Notion, Github and/or Google Drive \n \
 Install vim plugins by launching vim \n"
 
