#!/bin/bash
#
# Script name: pywal_start
# reset the colourscheme and set the wallpaper using pywal

rm -rf ~/.cache/wal
wal -i ~/Downloads/wallpaper.jpeg
cp ~/.cache/wal/colors.Xresources ~/.Xresources
xrdb ~/.Xresources
xdotool key super+shift+F5
