#!/bin/bash
#
# Script name: wallpaper_set
# from image named "art" generate the wallpaper using imagemagick, then regenerate colourscheme

convert ~/Downloads/art* -resize x540 ~/Downloads/art2.jpeg
convert ~/Downloads/art2.jpeg -resize 1920x1080^ -gravity center -extent 1920x1080 -blur 0x20 ~/Downloads/wallpaper.jpeg
convert ~/Downloads/wallpaper.jpeg -gravity center ~/Downloads/art2.jpeg -composite ~/Downloads/lockscreen.xpm
rm -rf ~/Downloads/art*
~/.scripts/pywal_start
